### ISSUE TITLE
Plugins and resources

### ISSUE THREAD

**Issue by Spomky** [matthiasnoback/symfony-bundle-plugins#10]
Hi,

I created a `FooBundle` and a `BarPlugin`.
`BarPlugin` is in folder `Plugin/BarPlugin` and contains resources such as translations and twig templates.
My problem is that I do not understand how to use my templates and my translations. These files do not seem to be loaded as if they are stored in a traditional bundle folder.

**Comment by matthiasnoback** [comment]
Nice, didn't think of that.
Plugins are not registered as "resource roots". You can't for example point to `@BarPlugin:Some:Template.html.twig` etc.
As far as I know, most resources can be referenced by absolute file path. And Twig supports aliassing for paths as well. Or you may look into Puli for a more generic solution for loading resources (http://docs.puli.io/en/latest/).

**Comment by Spomky** [comment]
I tried with Puli and it works (thanks for [your blog post](http://php-and-symfony.matthiasnoback.nl/2014/09/exposing-resources-from-bundles-to-packages/)).
Template mapping works fine, but I was not able to load translation catalogues. I decided to move them to the `Resources` folder at the root of the bundle.

**Comment by Spomky** [comment]
It is quite embarrassing, but I found that entity mapping fails as my XML files are not stored in `Resources/config/doctrine...` but in the folder of my plugin.
I know this is out of the scope of this bundle, but do you have any idea on how to fix this?

**Comment by matthiasnoback** [comment]
You could register a compiler pass to expose the mapping XML files (http://symfony.com/doc/current/cookbook/doctrine/mapping_model_classes.html).

**Comment by Spomky** [comment]
Thank you. You are awesome.

I tried to expose my model using a compiler pass and it works fine now.
The symfony doc you provided is helpful, but I also found that the FOSUserBundle uses the same way to expose its model.

EDIT:
Just for people who might be interested:

``` php
<?php

namespace Acme\FooBundle\Plugin\BarPlugin;

use Matthias\BundlePlugins\BundlePlugin;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass;
...

class BarPlugin implements BundlePlugin
{
    ...
    public function build(ContainerBuilder $container)
    {
        $mappings = array(
            realpath(__DIR__ . '/Resources/config/doctrine-mapping') => 'Acme\FooBundle\Plugin\BarPlugin\Model',
        );
        if (class_exists('Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass')) {
            $container->addCompilerPass(DoctrineOrmMappingsPass::createXmlMappingDriver($mappings, array()));
        }
    }
}
```

**Comment by matthiasnoback** [comment]
Thanks for letting me know. Good luck!

**Comment by xabbuh** [comment]
Wouldn't it be easier to do that [in your Doctrine configuration](http://symfony.com/doc/current/reference/configuration/doctrine.html#custom-mapping-entities-in-a-bundle)?

**Comment by Spomky** [comment]
@xabbuh yes, it is easier, but all developers that use my bundle have to modify their configuration and add these mappings.
This way is a little bit complicated for me, but developers just have to enable the bundle in the kernel and configure it => **DX is better**

**Comment by xabbuh** [comment]
I suggest to look into [prepending configurations](http://symfony.com/doc/current/cookbook/bundles/prepend_extension.html) then.

**Comment by Spomky** [comment]
This feature is not yet supported by this bundle (see #8).

Anyway, the solution suggested by @matthiasnoback works fine and is a very good solution for the goal to reach.
I have no reason to find another way to expose my mapping.

**Comment by magarzon** [comment]
In fact, in my fork https://github.com/magarzon/symfony-bundle-plugins/tree/feature/prepend_configs (I hope the PR will be merged soon), I've added prepending configuration feature.

And in my core plugin I have something similar to this:

```
public function prepend(ContainerBuilder $container)
{
        $loader = new ThirdPartyBundlesConfigLoader(new FileLocator(__DIR__.'/../Resources/config'));
        $thirdParty = $loader->load('third_party_bundles_config.yml');

        foreach($container->getExtensions() as $name => $extension) {
            if (isset($thirdParty[$name])) {
                $config = $thirdParty[$name];
                $container->prependExtensionConfig($name, $config);
            }
        }
}

```

I have third party bundles configuration in a config file. In prepend method it's loaded (with a helper class of my own, ThirdPartyBundlesConfigLoader), then all extensions (in fact, all bundles that are instantiated in AppKernel) are traversed, if there is a configuration for that extension/bundle, it's prepended.
