### ISSUE TITLE
Avoid CorePlugin

### ISSUE THREAD

**Issue by gregumo** [matthiasnoback/symfony-bundle-plugins#11]
Hi Matthias,
Thanks for this useful bundle.
I'm just a bit disapointed about using a CorePlugin to declare my services for the BundleWithPlugins. I'm wondering if you thought about a way to accomplish this in the main Bundle ?
If you think this is impossible, can you explain me why ?
Thanks !

**Comment by matthiasnoback** [comment]
It's possible, but you'd have to extend the extension class, the configuration class and then finally the bundle class provided by this library, so then you don't really need this library after all ;)

**Comment by matthiasnoback** [comment]
I'm closing this as there's no work to be done. Thanks.
