### ISSUE TITLE
Plugin system in the context of SF4

### ISSUE THREAD

**Issue by gregurco** [matthiasnoback/symfony-bundle-plugins#17]
Hello @matthiasnoback !
As you know, SF4 came with many changes. The whole bundle system was rethought and refactored with implementation of new flex system. Now bundles are installed through flex and defined in: https://github.com/symfony/demo/blob/master/config/bundles.php
They are not instantiated there... only class paths and environment where to use bundle are written. Next these bundles are instantiated in Kernel:  https://github.com/symfony/demo/blob/master/src/Kernel.php#L41
The main problem is that current system doesn't support passing any parameters in bundle constructor.
Do you have any idea, how to adapt plugin system to SF4? Or do you think that SF4 should allow to pass parameters to bundles constructor?
Thanks.

**Comment by matthiasnoback** [comment]
I have no idea, sorry! I thought that there were bundles out there that also use constructor arguments, but maybe not anymore. There should be other options, like relying on container parameters, or static properties. I really don't know :)

**Comment by gregurco** [comment]
Ok, thanks :slightly_smiling_face: I thought about compiler pass. I don't know if it's possible, I didn't check it yet, but to:
- check all connected bundles
- find which are plugins
- collect them somewhere (class like container)
- inject this container with all plugins in main bundle

For me it looks as option, but in this case plugins should be connected as simple bundles (not through constructor of main bundle)...

**Comment by gregurco** [comment]
So, I checked and it was stupid idea :slightly_frowning_face: Compiler passes are executed after all staff related to bundles build and used here... So, another option is to ask user to modify `config/bundles.php` file in a next way:
```php
<?php

return [
    ...
    DemoBundle::class => [
        'all' => true,
        'constructorArguments' => [[
            FooPlugin::class, // or new FooPlugin()
        ]]
    ],
];
```
and to add possibility to pass it to constructor:
```php 
# Modification in src/Kernel.php
...
    public function registerBundles()
    {
        $contents = require $this->getProjectDir().'/config/bundles.php';
        foreach ($contents as $class => $envs) {
            if (isset($envs['all']) || isset($envs[$this->environment])) {
                # yield new $class(); - was
                yield new $class(...$envs['constructorArguments'] ?? []); # - modification
            }
        }
    }
...
```
Both `config/bundles.php` and `src/Kernel.php` are created by symfony, but are in project (not vendor). I think user has full right to modify it and to add new features. With this fix current plugin system will work.

**Comment by matthiasnoback** [comment]
Thanks for sharing! It's not very elegant, but it may work. Let's leave it here for people looking for the same thing :)

**Comment by David-Maran** [comment]
I think modifying the Kernel file is not a good solution.
You need a plugin system independent of the symfony bundle system, with a configuration file and a plugin system autowire in config / bundle for dependency injection.

**Comment by matthiasnoback** [comment]
Thanks for your comment. This library has long lost its relevance though, so I'm finally closing this issue :)

**Comment by David-Maran** [comment]
Maybe put this library in read only?
