### ISSUE TITLE
Final methods in BundleWithPlugins

### ISSUE THREAD

**Issue by lolautruche** [matthiasnoback/symfony-bundle-plugins#4]
Hi

Any reason `__construct()` / `build()` / `boot()` are marked as `final` in `BundleWithPlugins`?
This adds a huge limitation for regular bundles that would use this system as it cannot override those methods any more, e.g. to add compiler passes or anything that is done at boot time, not talking about the constructor.

Big projects like eZ could not use the plugin system because of this limitation.
I'd do a PR of course, but I wanted to discuss this first :-)

**Comment by matthiasnoback** [comment]
Good question! I wanted to encourage the use of a separate plugin for these kinds of general things. That could be like a `CorePlugin` which you return from the bundle's `alwaysRegisteredPlugins()` method (you can see an example of this method in the [README file](https://github.com/matthiasnoback/symfony-bundle-plugins/blob/master/README.md)).

Just let me know if this is feasible for you. It's not a must for me to make these methods final. I guess only `getContainerExtension()` should be final, since it's not supposed to be overridden (you need to use the `ExtensionWithPlugins` class for it).

**Comment by lolautruche** [comment]
Thanks for your reply @matthiasnoback .
I understand the best practice to implement core plugins, but I believe this would restrain people to use this nice library as it enforces to refactor. In the case of eZ for instance, it would not be a simple refactoring at all (see [EzPublishCoreBundle](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php)).

> I guess only getContainerExtension() should be final, since it's not supposed to be overridden (you need to use the ExtensionWithPlugins class for it)

Here also I think this too limiting, see [EzPublishCoreExtension](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php).
I'm not saying we should not refactor in order to use SymfonyBundlePlugins, but as you can see we use required specific stuff... 

That's just an example :wink:

**Comment by matthiasnoback** [comment]
Okay, you convinced me that more flexibility is required. Would you provide a PR for this, removing the final keyword everywhere? ;)

**Comment by lolautruche** [comment]
Sure I can do a PR :smiley: , but I'm still not sure of how we can handle the extension case. Any hint?

**Comment by matthiasnoback** [comment]
Well, if you remove every `final` hint keyword, then you could just extend from the `ExtensionWithPlugins` class and do anything you like. Do you see any other specific problem?

**Comment by lolautruche** [comment]
Mmm seems fine. Anyway if I find other issues, I'll sure report and try to fix them :octocat:

**Comment by matthiasnoback** [comment]
Thanks! And thanks for adopting this library (if everything works out for you of course).

**Comment by lolautruche** [comment]
Et voilà: #5

Not sure we'll adopt your library, but we'll sure evaluate it for eZ Platform! :smile:
