### ISSUE TITLE
[Question] How to set a default (global) configuration

### ISSUE THREAD

**Issue by ad3n** [matthiasnoback/symfony-bundle-plugins#6]
Can you give me an example, how to set default configuration?

**Comment by matthiasnoback** [comment]
Could you describe your situation in a little bit more detail? What are you trying to accomplish?

**Comment by ad3n** [comment]
I want to add some default configuration such as:

``` php
main_bundle:
    config1: value1
    config2: value2
    plugin1:
        config1: value1
        config2: value2
```

**Comment by matthiasnoback** [comment]
There's no "main" configuration, you'd have to move that to a plugin (like a MainPlugin, or CorePlugin). Each plugin can have default configuration, just like a bundle can have default configuration (just use `defaultValue(...)`, etc.

**Comment by ad3n** [comment]
hhhmmm ok thanks for the answer... i think will be better to add some default config instead of plugin config

**Comment by matthiasnoback** [comment]
Closing this as there's no work to be done here. Thanks!
