### ISSUE TITLE
Configuration validation

### ISSUE THREAD

**Issue by Spomky** [matthiasnoback/symfony-bundle-plugins#9]
Hi,

I have a problem using this configuration.
Let say the configuration of my plugin `foo` is:

``` php
...
public function addConfiguration(ArrayNodeDefinition $pluginNode)
{
    $pluginNode
        ->children()
            ->scalarNode('class')
                ->cannotBeEmpty()->isRequired()
                ->validate()
                    ->ifTrue(function($value){
                        return !class_exists($value);
                    })
                    ->thenInvalid('The class does not exist')
                ->end()
            ->end()
        ->scalarNode('manager')->cannotBeEmpty()->defaultValue('default_manager')->end()
    ->end();
}
...
```

When I do not set the configuration properly, I should receive a message like `The configuration under 'bundle.foo.class' must be set`, but I have no configuration error. I only have an error because parameter `$pluginConfiguration['class']` is not set.

**Comment by matthiasnoback** [comment]
I see, well, the problem is that the plugin node itself is not required to be defined. So if it isn't, all the underlying validation rules are not applied (this is the case for regular bundle configurations as well). The solution is to call `->isRequired()` on the `$pluginNode` itself as well.

**Comment by matthiasnoback** [comment]
If this works for you, let me know, and I'll close this issue (which isn't really an issue with the package).

**Comment by Spomky** [comment]
Thanks! It works fine now.

**Comment by matthiasnoback** [comment]
Nice :)
